export const ROUNDS = [
    {
        round:       1,
        minCount:    4,
        maxCount:    6,
        mixed:       false,
        moving:      false,
        speed:       0,
        freezeAfter: 1200,
        showTime:    2500,   // ms objects shown before answering opens
        label:       'Count the cubes',
        shape:       'cube',
    },
    {
        round:       2,
        minCount:    5,
        maxCount:    7,
        mixed:       false,
        moving:      true,
        speed:       1.0,
        freezeAfter: null,
        showTime:    2500,
        label:       'Count the cubes',
        shape:       'cube',
    },
    {
        round:       3,
        minCount:    6,
        maxCount:    8,
        mixed:       false,
        moving:      true,
        speed:       1.6,
        freezeAfter: null,
        showTime:    2000,
        label:       'Count the pyramids',
        shape:       'pyramid',
    },
    {
        round:       4,
        minCount:    6,
        maxCount:    8,
        mixed:       true,
        moving:      false,
        speed:       0,
        freezeAfter: 1000,
        showTime:    2500,
        label:       'Count the 🔴 red shapes only',
        shape:       'torus',
    },
    {
        round:       5,
        minCount:    7,
        maxCount:    9,
        mixed:       true,
        moving:      true,
        speed:       1.8,
        freezeAfter: null,
        showTime:    2000,
        label:       'Count the 🔴 red shapes only',
        shape:       'mixed',
    },
    {
        round:       6,
        minCount:    8,
        maxCount:    10,
        mixed:       true,
        moving:      true,
        speed:       2.6,
        freezeAfter: null,
        showTime:    1800,
        label:       'Count the 🔴 red shapes only',
        shape:       'mixed',
    },
]

export const ANSWER_TIME = 6000  // snappier — 6s to answer